# Generated by Django 3.2.6 on 2021-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='stream',
            name='project_code',
            field=models.UUIDField(default='84989767-80db-4b66-b45b-ca4454d49d8a'),
        ),
    ]
