# Generated by Django 3.2.6 on 2021-09-08 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0002_auto_20210907_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='project_code',
            field=models.UUIDField(default='84989767-80db-4b66-b45b-ca4454d49d8a', editable=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
